version: "3.8"
services:
  client:
    container_name: client-dev
    image: client-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      - ./app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
